{% set version = "2.4.2" %}
# check testdata_version with `grep CURRENT_TEST_EXTRADATA_VERSION test/CMakeLists.txt`
{% set testdata_version = "20240719T1200" %}

package:
  name: fimex
  version: {{ version }}

source:
  - url: https://github.com/metno/fimex/archive/v{{ version }}.tar.gz
    sha256: 66303581baef197042e1d9e690720b937eb1fd7879eb976b9730e472c7e9be4b
    folder: source
  - url: https://rgw.met.no/0c541cf629a545769d10585a9ea2043f:unit-test-data/fimex-test-data-{{ testdata_version }}.tar.gz
    sha256: a002a2373eddcc34d6da0090b4e84e6fcd30d27202aac4c1c208f8dbeabf93d7
    folder: testdata

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.6
    - make         # [not win]
    - ninja        # [win]
    - pkg-config
  host:
    - howardhinnant_date >=2.4.1
    - mi-cpptest
    - eccodes
    - libnetcdf
    - libprotobuf
    - log4cpp
    - libxml2-devel
    - proj
    - udunits2
    - mi-programoptions
    # libnetcdf requires zlib when used via cmake while waiting for
    # https://github.com/conda-forge/libnetcdf-feedstock/pull/184
    - zlib
    # pypy builds seem to fail if libnsl is not listed here
    # cpython builds seem to install libnsl as dependency of some other package
    - libnsl
  run:
    - python
    - _openmp_mutex
    - eccodes
    - libnetcdf
    - libprotobuf
    - log4cpp
    - libxml2-devel
    - proj
    - udunits2
    - mi-programoptions

test:
  commands:
    - fimex --version
    - test -f $PREFIX/include/fimex/CDMconstants.h  # [unix]
    - test -f $PREFIX/lib/libfimex$SHLIB_EXT  # [unix]

about:
  home: https://wiki.met.no/fimex/start
  license: LGPL-2.1-or-later
  license_file: source/lgpl.txt
  summary: 'MET Norway File Interpolation, Manipulation and EXtraction library'
  dev_url: https://github.com/metno/fimex

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
