{% set version = "1.8.0" %}
# check testdata_version with `grep CURRENT_TEST_EXTRADATA_VERSION test/CMakeLists.txt`
{% set testdata_version = "20220211T1614" %}

package:
  name: fimex
  version: {{ version }}

source:
  - url: https://github.com/metno/fimex/archive/v{{ version }}.tar.gz
    sha256: 29564f14820bb32f08753a845d4c8440ad7f218b699b114d569e8a95fa675cea
    folder: source
  - url: https://wiki.met.no/_media/fimex/fimex-test-data-{{ testdata_version }}.tar.gz
    sha256: ab96bc4dc846fa4959660e56183ca467cf0f75f4dbdb42739f57d3a12afcd41e
    folder: testdata

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.6
    - make         # [not win]
    - ninja        # [win]
    - pkg-config
  host:
    - python
    - numpy
    - pybind11 >=2.2
    - pybind11-abi
    - howardhinnant_date >=2.4.1
    - mi-cpptest
    - eccodes
    - libnetcdf
    - log4cpp
    - libxml2
    - proj
    - udunits2
    - mi-programoptions
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - _openmp_mutex
    - eccodes
    - libnetcdf
    - log4cpp
    - libxml2
    - proj
    - udunits2
    - mi-programoptions

test:
  commands:
    - fimex --version
    - test -f $PREFIX/include/fimex/CDMconstants.h  # [unix]
    - test -f $PREFIX/lib/libfimex$SHLIB_EXT  # [unix]
  imports:
    - pyfimex0

about:
  home: https://wiki.met.no/fimex/start
  license: LGPL-2.1-or-later
  license_file: source/lgpl.txt
  summary: 'MET Norway File Interpolation, Manipulation and EXtraction library'
  dev_url: https://github.com/metno/fimex

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
