{% set version = "2.1.1" %}
# check testdata_version with `grep CURRENT_TEST_EXTRADATA_VERSION test/CMakeLists.txt`
{% set testdata_version = "20220211T1614" %}

package:
  name: fimex
  version: {{ version }}

source:
  - url: https://github.com/metno/fimex/archive/v{{ version }}.tar.gz
    sha256: a38972af7e382cab4d3298af69d82a872fdf20aaedf5f88c58a3f41caff31f69
    folder: source
  - url: https://wiki.met.no/_media/fimex/fimex-test-data-{{ testdata_version }}.tar.gz
    sha256: ab96bc4dc846fa4959660e56183ca467cf0f75f4dbdb42739f57d3a12afcd41e
    folder: testdata

build:
  number: 5
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.6
    - make         # [not win]
    - ninja        # [win]
    - pkg-config
  host:
    - python
    - numpy
    - pybind11 >=2.2
    - pybind11-abi
    - howardhinnant_date >=2.4.1
    - mi-cpptest
    - eccodes
    - libnetcdf
    - log4cpp
    - libxml2-devel
    - proj
    - udunits2
    - mi-programoptions
    # libnetcdf requires zlib when used via cmake while waiting for
    # https://github.com/conda-forge/libnetcdf-feedstock/pull/184
    - zlib
    # pypy builds seem to fail if libnsl is not listed here
    # cpython builds seem to install libnsl as dependency of some other package
    - libnsl
  run:
    - python
    - _openmp_mutex
    - eccodes
    - libnetcdf
    - log4cpp
    - libxml2-devel
    - proj
    - udunits2
    - mi-programoptions

test:
  commands:
    - fimex --version
    - test -f $PREFIX/include/fimex/CDMconstants.h  # [unix]
    - test -f $PREFIX/lib/libfimex$SHLIB_EXT  # [unix]
  imports:
    - pyfimex0

about:
  home: https://wiki.met.no/fimex/start
  license: LGPL-2.1-or-later
  license_file: source/lgpl.txt
  summary: 'MET Norway File Interpolation, Manipulation and EXtraction library'
  dev_url: https://github.com/metno/fimex

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
